### ISSUE TITLE
Support for GPT-3.5-Turbo

### ISSUE THREAD

**Issue by ciaran-regan-ie** [probcomp/GenGPT3.jl#12]
Great project!

I am trying to get it to work with `GPT-3.5-Turbo-Instruct` which is using the same legacy endpoint as `davinci-002`. However `GPT-3.5-Turbo-Instruct` does not work as is, as it requires the following two parameters to be changed, due to changes in OpenAI's API:
```
max_tokens=1
 echo=true
```

More generally, it would be nice to have support for newer models, such as GPT-4. I'd be willing to help with the changes.

**Comment by ztangent** [comment]
Hi @ciaran-regan-ie, unfortunately we can't support `gpt-3.5-turbo-instruct` or any newer models because OpenAI prohibit's the ability to query for the logprobs of user-specified text --- they only give logprobs for text that was generated server-side. GenGPT3.jl requires the ability to query logprobs of user-specified text to satisfy Gen's generative function interface, so `gpt-3.5-turbo-instruct` can't be used with Gen until OpenAI lifts their API restrictions.

**Comment by ciaran-regan-ie** [comment]
Hi @ztangent, thank you for the response! That's a shame! 

Are you interested in instead making it work with open source models? 

I've been trying to get this working with llama.cpp, as [they offer an API that is meant to mimic OpenAI's API](https://github.com/ggerganov/llama.cpp/blob/master/examples/server/README.md), but it seems the `echo` option has not been implemented. If this were implemented, I think this repo could be quite easily modified to point at a server running an open source model.

**Comment by ztangent** [comment]
Thanks for the question! You're right that `echo` needs to be supported. I may decide to get this working with open source models that are accessible via [together.ai](https://www.together.ai/) at some point, since they support almost the same JSON API as OpenAI models do, and they also support the `echo` option (and [returning prompt logprobs](https://docs.together.ai/docs/logprobs)).

The main issue with doing this is that GenGPT3.jl currently relies on the ability to tokenize the string locally before sending the token IDs to the server for probability evaluation (to avoid issues that arise when the same string has multiple tokenizations). And unfortunately I don't think there's tokenization code implemented in the Julia ecosystem for a large majority of open source model tokenizers (e.g. SentencePiece). It might be possible to refactor the library to avoid local tokenization, but there were issues that prevented me from doing that previously with the OpenAI models, and I haven't thought enough about whether it'd be possible for TogetherAI.
